package asl.console.ui2;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainWindow extends HorizontalLayout {
	protected CssLayout menuCssLayout;
	protected Button menuToggle;
	protected CssLayout mainMenu;
	protected Button aslHomeButton;
	protected Button dataTransferButton;
	protected Button logsButton;
	protected Button addFunctionality;
	protected CssLayout contentCsslayout;
	protected VerticalLayout contentVerticalLayout;
	protected Label pageTitleLabel;
	protected Table serversStateTable;
	protected Label authorsLabel;

	public MainWindow() {
		Design.read(this);
	}
}
